Добавлена полная логика по курсовой
kukuiski/MoneyScope pull request #1
Opened 2024-10-22 19:25 UTC by kukuiski

Добавлена полная логика, по одной функции из каждого блока, логирование, тестирование, README.md, конфиги линтеров и т.п.

2024-10-23 09:30 UTC, painassasin requested changes

2024-10-23 09:30 UTC, painassasin commented on .idea/.gitignore
Директорию .idea нужно удалить из отслеживания
```
git rm --cached .idea/ -r
```
и добавить в `.gitignore`

2024-10-23 09:30 UTC, painassasin commented on src/moneyscope/views.py
> +def get_greeting() -> str:
В модуле views нужно оставить только вьюшки - все вспомогательные должны быть в utils.py

2024-10-23 19:53 UTC, kukuiski commented on .idea/.gitignore
Сделал

2024-10-23 19:57 UTC, kukuiski commented on src/moneyscope/views.py
> +def get_greeting() -> str:
Сделал

2024-10-25 13:50 UTC, painassasin approved these changes

2024-10-25 13:50 UTC, painassasin commented on src/moneyscope/services.py
> +        if not data:
Кажется это можно вынести за блок try

2024-10-26 10:45 UTC, merged